### ISSUE TITLE
Correzione Milionario

### ISSUE THREAD

**Issue by marcellomaugeri** [Giuseppe-code/Programmazione-2#1]
Caro Giuseppe, grazie per il tuo codice. Ottima implementazione!

Qualche consiglio:

- In riga 24, nel commento, accenni al "costruttore di default". In realtà, quello è un costruttore come gli altri in quanto, il costruttore di default, per definizione, non ha parametri.
- Uno dei costruttori non inizializza il testo, sarà stata una svista.
- Nel terzo costruttore hai inserito comunque l'array delle risposte, in realtà uno dei costruttori nel testo prevedeva ben 6 parametri.
- Non hai salvato le risposte date in un file in output.

Per il resto buon lavoro!

**Comment by Giuseppe-code** [comment]
Va bene prof. Grazie mille! 
Vedrò di sistemare il prima possibile.
P.S. Realizzerò la dama prima del prossimo incontro.
